http://elastic:changeme@localhost:9220
POST /.kibana*/_search
{
  "aggs": {
    "types": {
      "terms": {
        "field": "type",
        "size": 100
      }
    }
  }
}

https://elastic:changeme@localhost:9200
POST /.kibana*/_search?size=100
{
  "query": {
    "match": {
      "type": "background-session"
    }
  }
}

https://elastic:changeme@localhost:9200
POST /.kibana*/_delete_by_query
{
  "query": {
    "match": {
      "type": "background-session"
    }
  }
}
