https://elastic:changeme@localhost:19200
GET /.kibana/_mapping



https://elastic:changeme@localhost:19200
POST /.kibana/_search
{
  "size": 0,
  "query": {
    "terms": {
      "type": [
        "dashboard",
        "visualization",
        "search",
        "index-pattern",
        "graph-workspace",
        "timelion-sheet"
      ]
    }
  },
  "aggs": {
    "types": {
      "terms": {
        "field": "type",
        "size": 10
      }
    }
  }
}
