http://elastic:changeme@localhost:9200
POST /.kibana_task_manager/_search
{ "query": { "match_all": {} } }

http://elastic:changeme@localhost:9200
POST /.reporting*/_delete_by_query
{ "query": { "match_all": {} } }

http://elastic:changeme@localhost:9200
POST /.kibana_task_manager/_delete_by_query
{ "query": { "match_all": {} } }

http://elastic:changeme@localhost:9200
POST /.kibana*/_delete_by_query
{ "query": { "match_all": {} } }

http://elastic:changeme@localhost:9200
DELETE /.kibana_task_manager*

http://elastic:changeme@localhost:9200
DELETE /.kibana*

http://elastic:changeme@localhost:9200
DELETE /.reporting*
