https://elastic:changeme@localhost:9200
GET /_cat/indices/.reporting*

https://elastic:changeme@localhost:9200
DELETE /.reporting-2021-11-14

https://elastic:changeme@localhost:9200
POST /.reporting*/_search
{
  "query": {
    "match_all": {}
  },
  "_source": {
    "excludes": ["output.content", "payload"]
  }
}

https://elastic:changeme@localhost:9200
POST /.reporting*/_count
{
  "query": {
    "match_all": {}
  }
}

https://elastic:changeme@localhost:9200
POST /.reporting*/_delete_by_query
{
  "query": {
    "match_all": {}
  }
}
