https://elastic:changeme@spicy.local:443
kbn-version: 8.0.0
POST /kbn/api/reporting/generate/printablePdf?jobParams=(browserTimezone:America%2FPhoenix,layout:(dimensions:(height:792,width:612),id:preserve_layout),objectType:'canvas%20workpad',relativeUrls:!(%2Fapp%2Fcanvas%23%2Fexport%2Fworkpad%2Fpdf%2Fworkpad-e720dc8e-aefb-4a6b-a226-0be62c3c0de3%2Fpage%2F1,%2Fapp%2Fcanvas%23%2Fexport%2Fworkpad%2Fpdf%2Fworkpad-e720dc8e-aefb-4a6b-a226-0be62c3c0de3%2Fpage%2F2,%2Fapp%2Fcanvas%23%2Fexport%2Fworkpad%2Fpdf%2Fworkpad-e720dc8e-aefb-4a6b-a226-0be62c3c0de3%2Fpage%2F3),title:'My%20Canvas%20Workpad%20-%20Status')
