http://elastic:changeme@localhost:9220
GET /_security/user/reporting_user

https://elastic:changeme@localhost:9200
GET /_cat/indices/

https://elastic:changeme@localhost:9200
DELETE /png_benchmarks-001

https://elastic:changeme@localhost:9200
POST /_forcemerge

#--------------------------------------------- 

https://elastic:changeme@localhost:19200
POST /.kibana_task_manager/_search?size=0
{
  "aggs": {
    "types": {
      "terms": {
        "field": "task.taskType",
        "size": 10
      }
    }
  }
}

https://elastic:changeme@localhost:19200
POST /.kibana_task_manager/_search
{
  "query": {
    "match": {
      "task.taskType": "reporting:execute"
    }
  }
}

http://elastic:changeme@localhost:9220
POST /.reporting-*/_search

http://elastic:changeme@localhost:9220
POST /.reporting-*/_search?filter_path=hits.hits._source.status,hits.hits._source.process_expiration,hits.hits._id,hits.hits._index
{
  "query": {
    "bool": {
      "filter": [
        {
          "range": {
            "process_expiration": {
              "lte": "now-15m"
            }
          }
        },
        {
          "bool": {
            "must_not": {
              "term": {
                "status": "completed"
              }
            }
          }
        }, {
          "bool": {
            "must_not": {
              "term": {
                "status": "failed"
              }
            }
          }
        }
      ]
    }
  }
}

https://elastic:changeme@localhost:19200
POST /.reporting-*/_search?size=50

#--------------------------------------------- 

https://elastic:changeme@localhost:9200
POST /.kibana*/_delete_by_query
{
  "query": {
    "match_all": {}
  }
}

https://elastic:changeme@localhost:19200
DELETE /metricb*

https://elastic:changeme@localhost:9200
DELETE /.kibana*

https://elastic:changeme@localhost:9200
DELETE /tests-001
DELETE /tests-002
DELETE /tests-003

https://elastic:changeme@localhost:19200
DELETE /.kibana_task*
 
https://elastic:changeme@localhost:19200
DELETE /kibana_sam*


https://elastic:changeme@localhost:19200
POST /_security/api_key
{ "name": "tim-is-cool" }

https://elastic:changeme@localhost:19200
GET /.kibana/_doc/index-pattern:aac3e500-f2c7-11ea-8250-fb138aa491e7

https://elastic:changeme@localhost:19200
GET /.kibana/_doc/search:bbe45ae0-f2c7-11ea-8250-fb138aa491e7

https://elastic:changeme@localhost:19200
GET /.kibana/_doc/non_default_space:search:22bebe20-e7ee-11ea-a730-d58e9ea7581b
